export const GET_TODO_LIST_START = 'GET_TODO_LIST_START';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_FAIL = 'GET_TODO_LIST_FAIL';

export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';
export const DELETE_TODO_ITEM_FAIL = 'DELETE_TODO_ITEM_FAIL';
export const DELETE_TODO_ITEM_START = 'DELETE_TODO_ITEM_START';

export const ADD_TODO_ITEM_SUCCESS = 'ADD_TODO_ITEM_SUCCESS';
export const ADD_TODO_ITEM_FAIL = 'ADD_TODO_ITEM_FAIL';
export const ADD_TODO_ITEM_START = 'ADD_TODO_ITEM_START';

export const UPDATE_TODO_ITEM_SUCCESS = 'UPDATE_TODO_ITEM_SUCCESS';
export const UPDATE_TODO_ITEM_FAIL = 'UPDATE_TODO_ITEM_FAIL';
export const UPDATE_TODO_ITEM_START = 'UPDATE_TODO_ITEM_START';

export const GET_TODO_ITEM_SUCCESS = 'GET_TODO_ITEM_SUCCESS';
export const GET_TODO_ITEM_FAIL = 'GET_TODO_ITEM_FAIL';
export const GET_TODO_ITEM_START = 'GET_TODO_ITEM_START';