export const GET_TODO_LIST_START = 'GET_TODO_LIST_START';
export const GET_TODO_LIST_SUCCESS = 'GET_TODO_LIST_SUCCESS';
export const GET_TODO_LIST_FAIL = 'GET_TODO_LIST_FAIL';

export const DELETE_TODO_ITEM_SUCCESS = 'DELETE_TODO_ITEM_SUCCESS';
export const DELETE_TODO_ITEM_FAIL = 'DELETE_TODO_ITEM_FAIL';
export const DELETE_TODO_ITEM_START = 'DELETE_TODO_ITEM_START';